--- 
- name: Show router configurations
  hosts: routers
  connection: network_cli
  gather_facts: no
  
  tasks:
  - name: gather ios_facts
    ios_facts:
    register: facts

  - name: print out the results of ios_facts
    debug:
      msg: "{{ facts }}"
