--- 
- name: Update banner message
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    banner_message: RUN AWAY RUN AWAY   SCARY RABBIT

  tasks:
  - name: "Update banner message to '{{ banner_message }}'"
    ios_config:
      lines:
        - "banner motd % {{ banner_message }} %"
